//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Count Enum")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("Count Enum")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2013")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("361c6ef7-b4e8-4b2c-a84a-a2fe0ed62855")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


